services:
  go_runner_service:
    container_name: go_runner_service
    image: golang
    build:
      dockerfile: service.Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mongo_express
      - runner_redis
      - amqp
    environment:
      SERVER: service
  go_runner_engine:
    container_name: go_runner_engine
    image: golang
    build:
      dockerfile: engine.Dockerfile
    ports:
      - "6969:6969"
    depends_on:
      - mongo_express
      - runner_redis
      - amqp
    environment:
      SERVER: engine
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    env_file:
      - ./.env
    volumes:
      - mongodb_data:/data/db
  mongo_express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    env_file:
      - ./.env
    depends_on:
      - mongodb
  runner_redis:
    container_name: runner_redis
    image: redis:alpine
    ports:
      - "6379:6379"
  amqp:
    container_name: rabbitmq_runner
    image: rabbitmq:4.1.1-management
    ports:
      - "5672:5672"
      - "15672:15672"
volumes:
  mongodb_data:
