package constants

import "time"

const (
	// Environment variables
	POSTGRES_HOST     = "POSTGRES_HOST"
	POSTGRES_PORT     = "POSTGRES_PORT"
	POSTGRES_USER     = "POSTGRES_USER"
	POSTGRES_PASSWORD = "POSTGRES_PASSWORD"
	POSTGRES_NAME     = "POSTGRES_NAME"

	REDIS_PASSWORD = "REDIS_PASSWORD"
	REDIS_HOST     = "REDIS_HOST"
	REDIS_PORT     = "REDIS_PORT"

	SERVER_PORT = "SERVER_PORT"
	SERVER_HOST = "SERVER_HOST"

	SECRET_KEY = "SECRET_KEY"

	ENV = "ENV"

	MONGO_HOST                      = "MONGO_HOST"
	MONGO_INITDB_ROOT_USERNAME      = "MONGO_INITDB_ROOT_USERNAME"
	MONGO_INITDB_ROOT_PASSWORD      = "MONGO_INITDB_ROOT_PASSWORD"
	ME_CONFIG_MONGODB_SERVER        = "ME_CONFIG_MONGODB_SERVER"
	ME_CONFIG_MONGODB_PORT          = "ME_CONFIG_MONGODB_PORT"
	ME_CONFIG_MONGODB_ADMINUSERNAME = "ME_CONFIG_MONGODB_ADMINUSERNAME"
	ME_CONFIG_MONGODB_ADMINPASSWORD = "ME_CONFIG_MONGODB_ADMINPASSWORD"
	ME_CONFIG_BASICAUTH_USERNAME    = "ME_CONFIG_BASICAUTH_USERNAME"
	ME_CONFIG_BASICAUTH_PASSWORD    = "ME_CONFIG_BASICAUTH_PASSWORD"

	CLIENT_ORIGIN_URL = "CLIENT_ORIGIN_URL"
	AUTH0_AUDIENCE    = "AUTH0_AUDIENCE"
	AUTH0_AUTHORITY   = "AUTH0_AUTHORITY"

	MGMT_AUTH0_CLIENT_ID     = "MGMT_AUTH0_CLIENT_ID"
	MGMT_AUTH0_CLIENT_SECRET = "MGMT_AUTH0_CLIENT_SECRET"
	MGMT_AUTH0_AUDIENCE      = "MGMT_AUTH0_AUDIENCE"

	RABBITMQ_HOST = "RABBITMQ_HOST"

	// Helpers
	MGMT_ACCESS_TOKEN     = "mgmtAccessToken"
	TOKEN_EXPIRY_TIME     = 23 * time.Hour
	EXCHANGE_NAME         = "runner"
	LIVE_LINES_QUEUE_NAME = "live_lines"

	MAX_GROUP_MEMBERS = 16
)
